pipeline {
    agent any

    environment {
        SERVICE_DIR     = 'server/heartbeat_service'
        IMAGE_NAME      = 'heartbeat-service:latest'
        CONTAINER_NAME  = 'heartbeat-service'
        DOCKERFILE_PATH = 'dockerfile'
    }

    options {
        timestamps()
    }

    stages {
        stage('Preparation') {
            steps {
                script {
                    env.SERVICE_DIR = fileExists('server/heartbeat_service/pom.xml') ? 'server/heartbeat_service' : 'heartbeat_service'
                }
            }
        }

        stage('Unit Tests') {
            when {
                beforeAgent true
                changeset "server/heartbeat_service/**"
            }
            steps {
                dir(env.SERVICE_DIR) {
                    sh 'chmod +x mvnw'
                }
            }
        }

        stage('Build Docker Image') {
            when {
                beforeAgent true
                changeset "server/heartbeat_service/**"
            }
            steps {
                dir(env.SERVICE_DIR) {
                    sh "docker build -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} ."
                }
            }
        }

        stage('Deploy') {
            when {
                beforeAgent true
                changeset "server/heartbeat_service/**"
            }
            steps {
                dir(env.SERVICE_DIR) {
                    sh "docker container rm -f ${CONTAINER_NAME} || true"
                    sh "docker run -d --name ${CONTAINER_NAME} --network host --restart unless-stopped ${IMAGE_NAME}"
                }
            }
        }

        stage('Cleanup') {
            when {
                beforeAgent true
                changeset "server/heartbeat_service/**"
            }
            steps {
                sh 'docker image prune -f'
            }
        }
    }
}
