# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iptool.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'iptool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ciptool.proto\x12\x06iptool\"1\n\x17GetNetworkConfigRequest\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\"\x91\x01\n\rNetworkConfig\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x13\n\x0bsubnet_mask\x18\x03 \x01(\t\x12\x0f\n\x07gateway\x18\x04 \x01(\t\x12\x0b\n\x03\x64ns\x18\x05 \x01(\t\x12!\n\x04mode\x18\x06 \x01(\x0e\x32\x13.iptool.NetworkMode\"A\n\x18GetNetworkConfigResponse\x12%\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x15.iptool.NetworkConfig\"C\n\x1aUpdateNetworkConfigRequest\x12%\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x15.iptool.NetworkConfig\"?\n\x1bUpdateNetworkConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x13SwitchToDhcpRequest\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\"8\n\x14SwitchToDhcpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*[\n\x0bNetworkMode\x12\x1c\n\x18NETWORK_MODE_UNSPECIFIED\x10\x00\x12\x17\n\x13NETWORK_MODE_MANUAL\x10\x01\x12\x15\n\x11NETWORK_MODE_DHCP\x10\x02\x32\x92\x02\n\x0eNetworkService\x12U\n\x10GetNetworkConfig\x12\x1f.iptool.GetNetworkConfigRequest\x1a .iptool.GetNetworkConfigResponse\x12^\n\x13UpdateNetworkConfig\x12\".iptool.UpdateNetworkConfigRequest\x1a#.iptool.UpdateNetworkConfigResponse\x12I\n\x0cSwitchToDhcp\x12\x1b.iptool.SwitchToDhcpRequest\x1a\x1c.iptool.SwitchToDhcpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iptool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKMODE']._serialized_start=529
  _globals['_NETWORKMODE']._serialized_end=620
  _globals['_GETNETWORKCONFIGREQUEST']._serialized_start=24
  _globals['_GETNETWORKCONFIGREQUEST']._serialized_end=73
  _globals['_NETWORKCONFIG']._serialized_start=76
  _globals['_NETWORKCONFIG']._serialized_end=221
  _globals['_GETNETWORKCONFIGRESPONSE']._serialized_start=223
  _globals['_GETNETWORKCONFIGRESPONSE']._serialized_end=288
  _globals['_UPDATENETWORKCONFIGREQUEST']._serialized_start=290
  _globals['_UPDATENETWORKCONFIGREQUEST']._serialized_end=357
  _globals['_UPDATENETWORKCONFIGRESPONSE']._serialized_start=359
  _globals['_UPDATENETWORKCONFIGRESPONSE']._serialized_end=422
  _globals['_SWITCHTODHCPREQUEST']._serialized_start=424
  _globals['_SWITCHTODHCPREQUEST']._serialized_end=469
  _globals['_SWITCHTODHCPRESPONSE']._serialized_start=471
  _globals['_SWITCHTODHCPRESPONSE']._serialized_end=527
  _globals['_NETWORKSERVICE']._serialized_start=623
  _globals['_NETWORKSERVICE']._serialized_end=897
# @@protoc_insertion_point(module_scope)
