# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import iptool_pb2 as iptool__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__

try:
    from grpc._utilities import first_version_is_lower
except ImportError:
    first_version_is_lower = None  # type: ignore[assignment]

if first_version_is_lower and first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION):
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in iptool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.',
        RuntimeWarning,
    )


class NetworkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNetworkConfig = channel.unary_unary(
                '/iptool.NetworkService/GetNetworkConfig',
                request_serializer=iptool__pb2.GetNetworkConfigRequest.SerializeToString,
                response_deserializer=iptool__pb2.GetNetworkConfigResponse.FromString,
                _registered_method=True)
        self.UpdateNetworkConfig = channel.unary_unary(
                '/iptool.NetworkService/UpdateNetworkConfig',
                request_serializer=iptool__pb2.UpdateNetworkConfigRequest.SerializeToString,
                response_deserializer=iptool__pb2.UpdateNetworkConfigResponse.FromString,
                _registered_method=True)
        self.SwitchToDhcp = channel.unary_unary(
                '/iptool.NetworkService/SwitchToDhcp',
                request_serializer=iptool__pb2.SwitchToDhcpRequest.SerializeToString,
                response_deserializer=iptool__pb2.SwitchToDhcpResponse.FromString,
                _registered_method=True)


class NetworkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNetworkConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNetworkConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchToDhcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNetworkConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkConfig,
                    request_deserializer=iptool__pb2.GetNetworkConfigRequest.FromString,
                    response_serializer=iptool__pb2.GetNetworkConfigResponse.SerializeToString,
            ),
            'UpdateNetworkConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNetworkConfig,
                    request_deserializer=iptool__pb2.UpdateNetworkConfigRequest.FromString,
                    response_serializer=iptool__pb2.UpdateNetworkConfigResponse.SerializeToString,
            ),
            'SwitchToDhcp': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchToDhcp,
                    request_deserializer=iptool__pb2.SwitchToDhcpRequest.FromString,
                    response_serializer=iptool__pb2.SwitchToDhcpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iptool.NetworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iptool.NetworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NetworkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNetworkConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iptool.NetworkService/GetNetworkConfig',
            iptool__pb2.GetNetworkConfigRequest.SerializeToString,
            iptool__pb2.GetNetworkConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNetworkConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iptool.NetworkService/UpdateNetworkConfig',
            iptool__pb2.UpdateNetworkConfigRequest.SerializeToString,
            iptool__pb2.UpdateNetworkConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchToDhcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iptool.NetworkService/SwitchToDhcp',
            iptool__pb2.SwitchToDhcpRequest.SerializeToString,
            iptool__pb2.SwitchToDhcpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
