# Generated by Django 5.2.5 on 2025-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setupconfig",
            name="password_hash",
        ),
        migrations.AddField(
            model_name="setupconfig",
            name="password_plain",
            field=models.CharField(default="RedSafe123", max_length=128),
        ),
    ]
