# Generated by Django 5.2.5 on 2025-09-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_remove_setupconfig_password_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoundUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=100, verbose_name="使用者名稱"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="綁定時間"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次上線"
                    ),
                ),
            ],
            options={
                "verbose_name": "綁定使用者",
                "verbose_name_plural": "綁定使用者",
                "ordering": ["-created_at"],
            },
        ),
    ]
