# Generated by Django 5.2.5 on 2025-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0003_bounduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgConfig",
            fields=[
                ("edge_id", models.TextField(primary_key=True, serialize=False)),
                ("edge_password", models.TextField()),
            ],
            options={
                "db_table": "config",
                "managed": False,
            },
        ),
    ]
